create table user (
   user_id bigint generated by default as identity,
   create_at date not null,
   user_email varchar(255) not null,
   user_password varchar(255) not null,
   user_salary double not null,
   user_type varchar(255) not null,
   primary key (user_id)
);

alter table user
    drop constraint if exists UK_j09k2v8lxofv2vecxu2hde9so;

alter table user
    add constraint UK_j09k2v8lxofv2vecxu2hde9so unique (user_email);